test:
  adapter: postgresql
  encoding: unicode
  database: eifoani_test
  host: localhost
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: eifoani_development
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: eifoani_production
  pool: 5
  username: eifoani
  password: